config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for :users
  root to: 'home#index'

  get 'search_clients', to: 'clients#search'
  get 'search_orders', to: 'orders#search'
  get 'plans', to: 'orders#plans'
  get 'values', to: 'orders#values'
  
  resources :orders, only: %i[index show edit update] do
    get 'canceled', to: 'orders#canceled', on: :collection
    get 'review_cancelation', to: 'orders#review_cancelation', on: :member
    patch :cancel_order , on: :member, as: 'cancel'
  end

  resources :commissions, only: %i[index]
    resources :sellers, only: %i[index new create show] do
    get 'commissions', on: :member
    patch :change_status, on: :member
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get '/orders/clients/:id', to: 'orders#clients', as: 'client'
      resources :orders, only: %i[show create] do
        patch 'pending', to: 'orders#pending'
        patch 'concluded', to: 'orders#concluded'
        patch 'canceled', to: 'orders#canceled'
      end
    end
  end
  
  resources :clients do
    resources :orders, only: %i[new create], on: :member
    get 'review_deactivation', to: 'clients#review_deactivation', on: :member
    patch :deactivate_cpf , on: :member
    patch :activate_cpf, on: :member
  end
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  before_action :authenticate_admin, only: %i[new create index commissions]
  before_action :authenticate_user!, only: %i[new create show index]

  def index
    @sellers = User.where(role: 'salesperson', status: :active)
    @inactive_sellers = User.where(role: 'salesperson', status: :inactive)
  end

  def show
    @seller = User.find(params[:id])
  end

  def new
    @seller = User.new
  end

  def create
    user_params = params.permit(:name, :email, :password, :password_confirmation, :status)
    @seller = User.new(user_params)

    if @seller.save
      redirect_to seller_path(@seller.id), notice: 'Vendedor cadastrado com sucesso'
    else
      flash.now[:alert] = 'Não foi possível registrar o vendedor'
      render 'new'
    end
  end

  def commissions
    @seller = User.find(params[:id])
    @commissions = Commission.where(user_id: @seller.id)
  end

  def change_status
    seller = User.find(params[:id])
    if seller.active?
      seller.inactive!
    else
      seller.active!
    end
    redirect_to seller_path(seller.id)
  end
end

app/views/sellers/commissions.html.erb
<h1 class="ls-title-intro ls-ico-trophy">Comissões</h1>


<div class="ls-box">
<h3 class="ls-title-3">Vendedor: <%= @seller.name %></h3>
<br>
<h3>Comissões</h3><br>

<% if @commissions.any? %>
  <table class="ls-table ls-table-striped ls-bg-header">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Nome do vendedor</th>
        <th scope="col">Valor</th>
        <th scope="col">Data de geração</th>
      </tr>
    </thead>
    <tbody>
      <% @commissions.each do |com| %>
        <tr id="<%= "id#{com.id}" %>">
          <td scope="row"><%= com.id %></td>
          <td scope="row"><%= User.find(com.user_id).name %></td>
          <td scope="row"><%= number_to_currency(com.value) %></td>
          <td scope="row"><%= "Gerada em #{com.created_at}" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h3 class="ls-alert-warning">Nenhuma comissão encontrada</h3>
<% end %>

</div>

app/views/sellers/index.html.erb
<h1 class="ls-title-intro ls-ico-panel-pabx">Vendedores</h1>
<%= link_to 'Cadastrar um vendedor', new_seller_path,  class: "ls-btn ls-btn-sm"  %>
<% if @sellers.empty? && @inactive_sellers.empty? %>
  <h2 class="ls-alert-warning">Nenhum vendedor cadastrado</h2>
<% else %>

  <% unless @sellers.empty? %>
    <table class="ls-table ls-table-striped ls-bg-header" id="active-sellers">
      <thead>
        <tr>
          <th scope="col">Nome</th>
          <th scope="col">E-mail</th>
          <th scope="col">Status</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <% @sellers.each do |seller| %>
          <tr id="seller-<%= seller.id %>">
            <td scope="row"> <%= link_to seller.name, seller_path(seller.id) %> </td>
            <td scope="row"> <%= seller.email %> </td>
            <td scope="row"> <%= User.human_enum_name(:status, seller.status) %> </td>
            <td scope="row"><%= link_to 'Ver detalhes', seller_path(seller.id), class: "ls-btn ls-btn-sm" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>

  <% unless @inactive_sellers.empty? %>
    <table class="ls-table ls-table-striped ls-bg-header" id="inactive-sellers">
      <thead id="ls-bg-header-inactive">
        <tr>
          <th scope="col">Nome</th>
          <th scope="col">E-mail</th>
          <th scope="col">Status</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <% @inactive_sellers.each do |seller| %>
          <tr id="seller-<%= seller.id %>">
            <td scope="row"> <%= link_to seller.name, seller_path(seller.id) %> </td>
            <td scope="row"> <%= seller.email %> </td>
            <td scope="row"> <%= User.human_enum_name(:status, seller.status) %> </td>
            <td scope="row"><%= link_to 'Ver detalhes', seller_path(seller.id), class: "ls-btn ls-btn-sm" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>

<% end %>

app/views/sellers/new.html.erb
<%= render partial: "partial/model_errors" , locals:{ model: @seller } %>
<h1 class="ls-title-intro ls-ico-user-add">Cadastro de vendedor</h1>

<div class= "ls-box"> 
  <%= form_with url: "/sellers" , html: {class: 'ls-form'} do |form| %>
    <fieldset>
      <%= form.label :name, 'Nome', class: 'ls-label ls-labels' %>
      <%= form.text_field :name, class:'col-md-5' %>
    </fieldset>

    <fieldset>
      <%= form.label :email, 'E-mail', class: 'ls-label ls-labels' %>
      <%= form.email_field :email, class:'col-md-5' %>
    </fieldset>

    <fieldset>
      <%= form.label :password, 'Senha', class: 'ls-label ls-labels' %>
      <%= form.password_field :password, class:'col-md-5' %>
    </fieldset>

    <fieldset>
      <%= form.label :password_confirmation, 'Confirme sua senha', class: 'ls-label ls-labels' %>
      <%= form.password_field :password_confirmation, class:'col-md-5' %>
    </fieldset>

    <fieldset class='radio'> 
      <%= radio_button_tag(:status, "active", class: "radio") %>
      <%= label_tag(:status, "Ativo") %>
      <br>
      <%= radio_button_tag(:status, "inactive", class: "radio") %>
      <%= label_tag(:status, "Inativo") %>
    </fieldset>

    <fieldset>
      <%= form.submit 'Cadastrar', class: 'ls-btn' %>
    </fieldset>
  <% end %>

</div>
<%= button_to 'Voltar', sellers_path, method: :get, class: "ls-btn ls-btn-sm" %>

app/views/sellers/show.html.erb
<h1 class="ls-title-intro ls-ico-user">Dados do vendedor <%= @seller.name %></h1>


<div class="ls-box">
  <h2 class="ls-title-name"><%= @seller.name %></h2>
  <div>
    
      <div class="ls-label col-md-6 col-lg-8">
        <h4 class="ls-label-text">E-mail</h4><br>
        <div class="ls-form-text"><%= @seller.email %></div>
      </div>

      <div class="ls-label col-md-6 col-lg-8">
        <h4 class="ls-label-text">Status:</h4>   <br>     
        <div class="ls-form-text"><%= User.human_enum_name(:status, @seller.status) %></div>         
      </div>
      <p> 
        <% if @seller.active? %>
          <%= button_to 'Desativar vendedor', change_status_seller_path, {method: 'patch',  class: "ls-btn ls-btn-sm"}   %>
        <% else %>
          <%= button_to 'Ativar vendedor', change_status_seller_path, {method: 'patch',  class: "ls-btn ls-btn-sm"}   %>
        <% end %>
      </p>
  </div>
</div>

<%= button_to 'Voltar', sellers_path, method: :get, class: "ls-btn ls-btn-sm" %>