config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for :users
  root to: 'home#index'

  get 'search_clients', to: 'clients#search'
  get 'search_orders', to: 'orders#search'
  get 'plans', to: 'orders#plans'
  get 'values', to: 'orders#values'
  
  resources :orders, only: %i[index show edit update] do
    get 'canceled', to: 'orders#canceled', on: :collection
    get 'review_cancelation', to: 'orders#review_cancelation', on: :member
    patch :cancel_order , on: :member, as: 'cancel'
  end

  resources :commissions, only: %i[index]
    resources :sellers, only: %i[index new create show] do
    get 'commissions', on: :member
    patch :change_status, on: :member
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get '/orders/clients/:id', to: 'orders#clients', as: 'client'
      resources :orders, only: %i[show create] do
        patch 'pending', to: 'orders#pending'
        patch 'concluded', to: 'orders#concluded'
        patch 'canceled', to: 'orders#canceled'
      end
    end
  end
  
  resources :clients do
    resources :orders, only: %i[new create], on: :member
    get 'review_deactivation', to: 'clients#review_deactivation', on: :member
    patch :deactivate_cpf , on: :member
    patch :activate_cpf, on: :member
  end
end

app/models/client.rb
class Client < ApplicationRecord
  include ActiveModel::Validations
  enum eni_status: { inactive: 0, active: 1 }

  has_many :orders, dependent: nil

  validates :eni, :name, :email, presence: true
  # rubocop:disable all
  validates :eni, uniqueness: true
  # rubocop:enable all
  validates :eni, eni: true
  validates :eni, format: { with: /\A[0-9]+\z/, message: 'Somente números' }
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_user!, only: [:index]
  before_action :authenticate_admin, only: %i[review_deactivation deactivate_cpf activate_cpf]
  before_action :authenticate_status

  def index
    @clients = Client.where(eni_status: :active)
    @inactive_clients = Client.where(eni_status: :inactive)
  end

  def show
    @client = Client.find(params[:id])
  end

  def search
    @client = Client.find_by eni: params[:query]
    if @client
      redirect_to client_path(@client.id)
    else
      flash[:alert] = 'Cliente não encontrado'
      redirect_to clients_path
    end
  end

  def new
    @client = Client.new
  end

  def create
    client_params = params.require(:client).permit(:eni, :name, :email)
    @client = Client.new(client_params)
    if @client.save
      redirect_to clients_path, notice: 'Cliente cadastrado com sucesso'
    else
      flash.now[:alert] = 'Não foi possível registrar o cliente'
      render 'new'
    end
  end

  def review_deactivation
    @client = Client.find(params[:id])
  end

  def deactivate_cpf
    client = Client.find(params[:id])
    update_params = params.permit(:cancellation_reason)
    return unless client.update(update_params)

    client.inactive!
    redirect_to client_path(client.id), alert: 'Cliente bloqueado'
  end

  def activate_cpf
    client = Client.find(params[:id])
    return unless client.inactive?

    client.active!
    redirect_to client_path(client.id), notice: 'Cliente desbloqueado com sucesso'
  end
end

app/views/clients/index.html.erb
<h1 class="ls-title-intro ls-ico-users">Clientes</h1>

<div >
  <%= link_to 'Cadastrar novo cliente', new_client_path, class: "ls-btn ls-btn-sm" %>
</div>

<div class= "ls-box-filter">
  <%= form_with url: search_clients_path, method: :get, html: {class: 'ls-form'} do %>
    <%= label_tag :query, 'CPF do cliente', class: 'ls-label col-md-2' %><br>
    <%= text_field_tag :query %>
    <%= submit_tag 'Buscar', class: 'ls-btn-primary' %>
  <% end %>
</div>

<% if @clients.empty? &&  @inactive_clients.empty?%>
  <h2 class="ls-alert-warning">Nenhum cliente cadastrado</h2>
<% else %>

  <% unless @clients.empty?  %>
    <table id = "active-clients" class="ls-table ls-table-striped ls-bg-header">
      <thead>
        <tr>
          <th scope="col">Nome</th>
          <th scope="col">E-mail</th>
          <th scope="col"></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <% @clients.each do |client| %>
          <tr id="client-<%= client.id %>">
            <td scope="row"><%= link_to client.name, client_path(client.id), class: "index-link" %></td>
            <td scope="row"><%= client.email %></td>
            <td scope="row"><%= link_to 'Fazer pedido', new_client_order_path(client.id), class: "ls-btn ls-btn-sm" %></td>          
            <td scope="row"><%= link_to 'Ver detalhes', client_path(client.id), class: "ls-btn ls-btn-sm"  %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>

  <% unless @inactive_clients.empty?  %>
    <table id = "inactive-clients" class="ls-table ls-table-striped ls-bg-header">
      <thead id="ls-bg-header-inactive">
        <tr>
          <th scope="col">Nome</th>
          <th scope="col">E-mail</th>
          <th scope="col"></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <% @inactive_clients.each do |client| %>
          <tr id="client-<%= client.id %>">
            <td scope="row"><%= link_to client.name, client_path(client.id), class: "index-link" %></td>
            <td scope="row"><%= client.email %></td>
            <td scope="row">Cliente Bloqueado</td>          
            <td scope="row"><%= link_to 'Ver detalhes', client_path(client.id), class: "ls-btn ls-btn-sm"  %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
 

<% end %>

app/views/clients/new.html.erb
<h1 class="ls-title-intro ls-ico-user-add">Novo Cliente</h1>
<%= render partial: "partial/model_errors" , locals:{ model: @client } %>

<div class= "ls-box"> 
  <%= form_with model: @client, html: {class: 'ls-form'} do |form| %>
    <fieldset>
      <%= form.label :eni, class: 'ls-label ls-labels' %>
      <%= form.text_field :eni, class:'col-md-5', placeholder: 'Somente números'%>
    </fieldset>
    <fieldset>
      <%= form.label :name, class: 'ls-label ls-labels' %>
      <%= form.text_field :name, class:'col-md-5' %>
    </fieldset>
    <fieldset>
      <%= form.label :email, class: 'ls-label ls-labels' %>
      <%= form.text_field :email, class:'col-md-5' %>
    </fieldset>
    <fieldset class='btn-submit'>
      <%= form.submit 'Cadastrar', class: 'ls-btn' %>
    </fieldset>
  <% end %>
</div>
<%= button_to 'Voltar', clients_path, method: :get, class: "ls-btn ls-btn-sm" %>

app/views/clients/review_deactivation.html.erb
<h1 class="ls-title-intro ls-ico-user">Bloqueio de cliente</h1>
<div class= "ls-box"> 
  <h2 class="ls-title-name"><%= @client.name %></h2>

  <div>
    <div class="ls-label col-md-6 col-lg-8">
      <h4>CPF:</h4>
      <div class="ls-form-text"><%= @client.eni %></div>
    </div>

    

    <div class="ls-label col-md-6 col-lg-8">
      <h4>Email</h4>
      <div class="ls-form-text"><%= @client.email %></div>
    </div>

    
  </div>
</div>
<h3 class="ls-alert-warning">Tem certeza que deseja Bloquear este cliente?</h3>

<div class= "ls-box-filter">
  <%= form_with url: "/clients/#{@client.id}/deactivate_cpf", method: :patch, html: {class: 'ls-form'} do |form| %>
    <%= form.label :cancellation_reason, 'Motivo:' %>
    <%= form.text_area :cancellation_reason %>
    <%= form.submit 'Confirmar', class: "ls-btn-primary-danger" %>
  <% end %>
</div>
<%= button_to 'Voltar', client_path(@client.id), method: :get, class: "ls-btn ls-btn-sm" %>

 

app/views/clients/show.html.erb
<h1 class="ls-title-intro ls-ico-user">Dados do cliente <%= @client.name %></h1>

<div class="ls-box">
  <h2 class="ls-title-name"><%= @client.name %></h2>
  <div><br>
    
      <div class="ls-label col-md-6 col-lg-8">
        <h4 class="ls-label-text">CPF:</h4><br>
        <div class="ls-form-text"><%= @client.eni %></div>
      </div><br>

      <div class="ls-label col-md-6 col-lg-8">
        <h4 class="ls-label-text">Status do CPF:</h4><br>
      
        <% if @client.active? %>
          <div class="ls-form-text">CPF ativo</div><br>
        <% else %>
          <div class="ls-form-text">CPF inativo</div><br>
        <% end %>
      </div>

      <div class="ls-label col-md-6 col-lg-8">
        <h4 class="ls-label-text">Email</h4><br>
        <div class="ls-form-text"><%= @client.email %></div><br>
      </div>
      <% unless current_user.salesperson? %>
        <% if @client.active? %>
          <%= button_to 'Inativar CPF', review_deactivation_client_path(@client.id), method: :get, class: "ls-btn ls-btn-sm" %>
        <% else %>

        <h3 class="ls-alert-warning">O cliente se encontra bloqueado. Entre em contato com o nosso atendimento</h3><br>
          <div class="ls-label col-md-6 col-lg-8">
            <div class="ls-label-text">Motivo:</div><br>
            <div class="ls-form-text"><%= @client.cancellation_reason %></div><br><br>
            <%= button_to 'Reativar CPF', activate_cpf_client_path(@client.id), {method: 'patch', class: "ls-btn ls-btn-sm"}%>
          </div>
        <% end %>
      <% end %>
  </div>
</div>
<%= button_to 'Voltar', clients_path, method: :get, class: "ls-btn ls-btn-sm" %>