config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for :users
  root to: 'home#index'

  get 'search_clients', to: 'clients#search'
  get 'search_orders', to: 'orders#search'
  get 'plans', to: 'orders#plans'
  get 'values', to: 'orders#values'
  
  resources :orders, only: %i[index show edit update] do
    get 'canceled', to: 'orders#canceled', on: :collection
    get 'review_cancelation', to: 'orders#review_cancelation', on: :member
    patch :cancel_order , on: :member, as: 'cancel'
  end

  resources :commissions, only: %i[index]
    resources :sellers, only: %i[index new create show] do
    get 'commissions', on: :member
    patch :change_status, on: :member
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get '/orders/clients/:id', to: 'orders#clients', as: 'client'
      resources :orders, only: %i[show create] do
        patch 'pending', to: 'orders#pending'
        patch 'concluded', to: 'orders#concluded'
        patch 'canceled', to: 'orders#canceled'
      end
    end
  end
  
  resources :clients do
    resources :orders, only: %i[new create], on: :member
    get 'review_deactivation', to: 'clients#review_deactivation', on: :member
    patch :deactivate_cpf , on: :member
    patch :activate_cpf, on: :member
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum status: { pending: 0, concluded: 2, canceled: 3 }

  validates :plan_id, :period, :client_eni, presence: true

  belongs_to :client
  belongs_to :user, optional: true
end

app/controllers/api/v1/orders_controller.rb
class Api::V1::OrdersController < Api::V1::ApiController
  def show
    order = Order.find_by(params[:id])
    if order
      render json: order.as_json(except: %i[created_at updated_at cancelation_reason]), status: 200
    else
      render json: '{"error": "Objeto não encontrado"}', status: 404
    end
  end

  def create
    order_params = params.permit(:plan_id, :period, :value, :client_eni)
    order = Order.new(order_params)
    client = Client.find_by(eni: order.client_eni)
    order.client_id = client.id unless client.nil? || client.inactive?

    if order.save
      render json: order.as_json, status: 201
    elsif client.nil?
      render status: 422, json: '{"error": "Cliente não encontrado no sistema"}'
    elsif client.inactive?
      render status: 422, json: '{"error": "CPF do cliente está inativo no sistema"}'
    else
      render status: 422, json: order.errors.full_messages
    end
  end

  def clients
    client = Client.find_by(eni: params[:id])
    return return404 if client.nil?

    client_orders = client.orders
    if client_orders.empty?
      render json: '{"alert": "Nenhum pedido registrado"}', status: 200
    else
      render json: client_orders.as_json(except: %i[created_at updated_at cancelation_reason]), status: 200
    end
  end

  def concluded
    order = Order.find(params[:order_id])
    return render json: '{"alert": "Pedido já foi cancelado"}', status: 200 if order.canceled?

    order.concluded!
    Commission.generate(order)
    render json: order.as_json(except: %i[created_at updated_at cancelation_reason]), status: 200
  end

  def pending
    order = Order.find(params[:order_id])
    return render json: '{"alert": "Pedido já foi cancelado"}', status: 200 if order.canceled?

    order.pending!
    Commission.clear(order)
    render json: order.as_json(except: %i[created_at updated_at cancelation_reason]), status: 200
  end

  def canceled
    order = Order.find(params[:order_id])
    return render json: '{"alert": "Pedido não pode ser cancelado"}', status: 200 unless order.pending?

    order.canceled!
    order.update(cancelation_reason: 'Pedido cancelado pelo sistema de clientes') if order.canceled?
    Commission.clear(order)
    render json: order.as_json(except: %i[created_at updated_at]), status: 200
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!, only: %i[new index]
  before_action :authenticate_admin, only: %i[search]
  before_action :verify_ownership, only: %i[review_cancelation cancel_order]
  before_action :authenticate_status

  def new
    @client_id = params[:client_id]
    @order = Order.new
    @client = Client.find(@client_id)
    @api_produtos = api_check(Rails.configuration.apis['products_api'])
  end

  def create
    @order = Order.new(
      plan_id: params['client']['plan_id'],
      client_id: params['client']['client_id'],
      user_id: params['client']['user_id'],
      value: params['client']['value'],
      period: params['client']['period'],
      client_eni: params['client']['client_eni'],
      discount: params['client']['discount']
    )

    redirect_to order_path(@order.id), notice: 'Pedido cadastrado com sucesso!' if @order.save
  end

  def show
    @order = Order.find(params[:id])
    @client = Client.find(@order.client_id)
    @plan = Plan.find(@order.plan_id.to_s)
    @period = @order.period
    @price = @order.value
  end

  def index
    @users = User.where(role: 'salesperson')
    @orders = if current_user.salesperson?
                Order.where(user_id: current_user.id, status: :pending)
                     .or(Order.where(user_id: current_user.id, status: :concluded))
              else
                Order.where(status: :pending).or(Order.where(status: :concluded))
              end
  end

  def canceled
    @users = User.where(role: 'salesperson')
    @orders = if current_user.salesperson?
                Order.where(user_id: current_user.id, status: :canceled)
              else
                Order.where(status: :canceled)
              end
  end

  def review_cancelation
    @order = Order.find(params[:id])
    @client = Client.find(@order.client_id)
    @plan = Plan.find(@order.plan_id)
    @period = @order.period
    @price = @order.value
  end

  def cancel_order
    order = Order.find(params[:id])
    update_params = params.permit(:cancelation_reason)
    if update_params.values[0].empty?
      return redirect_to review_cancelation_order_path(order.id), alert: 'Motivo não pode ficar em branco'
    end

    api_domain = Rails.configuration.apis['clients_api']
    response = Faraday.patch("#{api_domain}/api/v1/cancelation/#{order.id}")

    case response.status
    when 200
      order.update(update_params)
      order.canceled!
      redirect_to canceled_orders_path, alert: 'Pedido Cancelado'
    when 406
      redirect_to review_cancelation_order_path(order.id), alert: 'O pedido já se encontra concluído'
    else
      redirect_to review_cancelation_order_path(order.id), alert: 'Não foi possível conectar com o sistema de clientes'
    end
  end

  def search
    if params[:query].present?
      id_user = User.find_by('name LIKE ?', "%#{params[:query]}%")
      id_client = Client.find_by('name LIKE ?', "%#{params[:query]}%")
      @orders = Order.where('user_id = ? or client_id = ?', id_user, id_client)
    else
      @orders = Order.all
    end
  end

  private

  def verify_ownership
    order = Order.find(params[:id])
    return if current_user == order.user || current_user.admin?

    redirect_to orders_path, alert: 'Acesso não permitido'
  end

  def api_check(path)
    Faraday.get(path)
    true
  rescue StandardError
    false
  end
end

app/views/orders/_orders_table.html.erb
<div>
  <% if @orders.empty? %>
    <h2 class="ls-alert-warning">Nenhum pedido</h2>
  <% else %>  
    <table class="ls-table ls-table-striped ls-bg-header">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Vendedor</th>
          <th scope="col">Cliente</th>
          <th scope="col">Status</th>
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
          <tr id="order-<%= order.id %>">
            <td scope="row"><%= link_to order.id, order_path(order.id), class: 'ls-btn ls-btn-primary ls-btn-sm', style: 'width: 50px' %></td>
            <td scope="row"><%= order.user.nil? ? '(sem vendedor)' : order.user.name  %></td>
            <td scope="row"><%= order.client.name %></td>
            <td scope="row"><%= Order.human_enum_name(:status, order.status) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/orders/canceled.html.erb
<h1 class="ls-title-intro ls-ico-edit-admin">Pedidos Cancelados</h1>

<div class= "ls-box-filter">
  <%= form_with url: search_orders_path, 
                method: :get, 
                html: {class: 'ls-form ls-form-inline'} do |f| %>
    <fieldset class='search'>
      <%= f.text_field :query, id: 'search', placeholder: 'Vendedor ou cliente' %>
      <%= f.submit 'Buscar', class: 'ls-btn-primary' %>
    </fieldset>
  <% end %>
</div>

<%= button_to 'Voltar', orders_path, method: :get, class: "ls-btn ls-btn-sm" %>
<%= render partial: 'orders_table', locals: { orders: @orders } %>

app/views/orders/index.html.erb
<h1 class="ls-title-intro ls-ico-edit-admin">Pedidos</h1>

<div class= "ls-box-filter">
  <%= form_with url: search_orders_path, 
                method: :get, 
                html: {class: 'ls-form ls-form-inline'} do |f| %>
    <fieldset class='search'>
      <%= f.text_field :query, id: 'search', placeholder: 'Vendedor ou cliente' %>
      <%= f.submit 'Buscar', class: 'ls-btn-primary' %>
    </fieldset>
  <% end %>
</div>

<%= button_to 'Pedidos cancelados', canceled_orders_path, method: :get, class: "ls-btn ls-btn-sm"  %>
<%# button_to 'Voltar', client_path(@client.id), method: :get, class: "ls-btn ls-btn-sm" %>

<%= render partial: 'orders_table', locals: { orders: @orders } %>

app/views/orders/new.html.erb
<div id="orderError" class="alert ls-alert-danger"></div>
<h1 class="ls-title-intro ls-ico-edit-admin">Cadastro de novo pedido</h1>

<%= link_to 'Cadastrar novo cliente', new_client_path,  class: "ls-btn ls-btn-sm" %><br><br>

<%= javascript_pack_tag "handleOrders" %>

<% if @api_produtos %>
  <% if @client.active? %>

    <div class="ls-box box">
      <form id="orderForm" class="ls-form " >
        <input type="hidden" name="client_id" value="<%= @client.id %>">
        <input type="hidden" name="client_name" value="<%= @client.name %>">
        <input type="hidden" name="client_eni" value="<%= @client.eni %>">
        <input type="hidden" name="user_id" value="<%= current_user.id %>">
        <input type="hidden" name="user_name" value="<%= current_user.name %>">
        <input type="hidden" name="domain_products" value="<%= Rails.configuration.apis['products_api'] %>">
        <input type="hidden" name="domain_payments" value="<%= Rails.configuration.apis['payments_api'] %>">
        <label for="group" class="ls-label-text">Grupo</label>
        <select name="group" id="group" class="dropdown">
        </select>
        <br><br>
        <label for="plan" class="ls-label-text">Plano</label>
        <select name="plan" id="plan" class="dropdown">
        </select>
        <br><br>
        <label for="period" class="ls-label-text">Periodicidade</label>
        <select name="period" id="period" class="dropdown">
        </select>
        <br><br>
        <label for="cupom_code">Cupom</label>
        <input type="text" name="cupom_code" id="cupom_code" disabled>
        <button id="submitCupom" class="ls-btn-primary" disabled>Validar cupom</button>
      </form>
    </div>
    <br><br>
    <div class="ls-box box" >
      <h3>Resumo do pedido:</h3>
      <br><br>
      <h4>Cliente:</h4> <span id="show_client"></span>
      <br><br>
      <h4>Vendedor:</h4> <span id="show_user"></span>
      <br><br>
      <h4>Valor:</h4> R$ <span id="show_price">0,00</span>
      <br><br>
      <h4>Desconto de cupom:</h4> R$ <span id="show_discount">0,00</span>
      <br><br>
    </div>
    <button id="submit" class="ls-btn-primary" >Salvar</button><br><br>
    <%= button_to 'Voltar', orders_path, method: :get, class: "ls-btn ls-btn-sm" %>
  <% else %>
    <h2 class="ls-alert-warning">Este cliente está bloqueado</h2>
  <% end %>

<% else %>
  <h2 class="ls-alert-warning">Houve um erro de conexão com o servidor (erro de conexão com API)</h2>
<% end %>

app/views/orders/plans.html.erb
<h1 class="ls-title-intro ls-ico-edit-admin">Cadastro de novo pedido</h1>
<%= link_to 'Cadastrar novo cliente', new_client_path,  class: "ls-btn ls-btn-sm" %><br><br>

<div class= "ls-box box">
  <% if @plans.nil? %>
    <h2 class="ls-alert-warning">Houve um erro de conexão com o servidor</h2>
  <% elsif @plans.empty? %>
    <h2 class="ls-alert-warning">Nenhum plano cadastrado</h2>
  <% else %>
    <%= form_with model: [@client, @order],
                  url: values_path,
                  html: { class: 'ls-form ls-form-horizontal' },
                  method: :get do |form| %>
      <%= form.hidden_field :client_id, value: @client_id %>
      <%= form.hidden_field :user_id, value: current_user.id %>

      <fieldset>
        <%= form.label :plan_id, 'Planos', class: 'ls-label' %>

          <div class="dropdown">
            <%= form.collection_select :plan_id, @plans, :id, :name %>
          </div>

        <%= form.submit 'Próximo',  class: "ls-btn ls-btn-sm" %>
      </fieldset>
    <% end %>
  <% end %>
</div>
<%= link_to 'Voltar', :back, class: 'ls-btn ls-btn-sm', style: 'margin-top: -15px' %>

app/views/orders/review_cancelation.html.erb
<h1 class="ls-title-intro ls-ico-edit-admin">Confirmar cancelamento de pedido</h1>


<div class= "ls-box box">
  <div>
    
    <div class="ls-title-3">Cliente</div><br>
    <div class="ls-label-text "><%= @client.name %></div><br>
    <div class="ls-form-text"><%= @client.eni %></div><br>
   
    <div class="ls-title-3">Plano</div><br>
    <div class="ls-label-text "><%= @plan.name %></div><br>


    <div class="ls-title-3">Periodicidade</div><br>
    <div class="ls-label-text "><%= @period %></div><br>


    <div class="ls-title-3">Valor</div><br>
    <div class="ls-label-text "><%= number_to_currency(@price) %></div><br>

  </div>
</div>

<h3 class="ls-alert-warning">Tem certeza que deseja cancelar esse pedido?</h3>

<div class= "ls-box-filter">
  <%= form_with url: "/orders/#{@order.id}/cancel_order", method: :patch, html: {class: 'ls-form'} do |form| %>
    <%= form.label :cancelation_reason, 'Motivo:' %>
    <%= form.text_area :cancelation_reason %>
    <%= form.submit 'Cancelar', class: "ls-btn-primary-danger" %>
  <% end %>
</div>

<%= button_to 'Voltar', orders_path, method: :get, class: "ls-btn ls-btn-sm" %>

app/views/orders/search.html.erb
<h1 class="ls-title-intro ls-ico-user">Pedidos</h1>

<%= render partial: 'orders_table', locals: { orders: @orders } %>

app/views/orders/show.html.erb
<h1 class="ls-title-intro ls-ico-edit-admin">Pedido</h1>


<div class= "ls-box box">
  <div>
    
    <div class="ls-title-3">Cliente</div><br>
    <div class="ls-label-text "><%= @client.name %></div><br>
    <div class="ls-form-text"><%= @client.eni %></div><br>
   
    <div class="ls-title-3">Plano</div><br>
    <div class="ls-label-text "><%= @plan.name %></div><br>


    <div class="ls-title-3">Periodicidade</div><br>
    <div class="ls-label-text "><%= @period %></div><br>


    <div class="ls-title-3">Valor</div><br>
    <div class="ls-label-text "><%= number_to_currency(@price) %></div><br>

    <div class="ls-title-3">Desconto</div><br>
    <div class="ls-label-text "><%= number_to_currency(@order.discount) %></div><br>

    <div class="ls-title-3">Status do pedido</div><br>
    <div class="ls-label-text "><%= Order.human_enum_name(:status, @order.status) %></div><br>

  </div>
</div>

<%= button_to 'Voltar', orders_path, method: :get, class: "ls-btn ls-btn-sm" %>
<br>
<%= link_to 'Cancelar pedido', review_cancelation_order_path, method: :get, class: "ls-btn-primary-danger ls-ico-remove" %>

app/views/orders/values.html.erb
<h1 class="ls-title-intro ls-ico-user">Cadastro de novo pedido</h1>
<%= link_to 'Cadastrar novo cliente', new_client_path, class: "ls-btn ls-btn-sm" %><br><br>

<div class= "ls-box box">
  <% if @prices.nil? %>
    <h2 class="ls-alert-warning">Houve um erro de conexão com o servidor</h2>
  <% elsif @prices.empty? %>
    <h2 class="ls-alert-warning">Nenhuma periodicidade cadastrada para este plano</h2>
  <% else %>
    <h3 class="ls-title-5"><%= @client.name %></h3>
    <h4 class="ls-title "><%= @plan.name %></h4>
  
    <%= form_with model: [@order, @client],
                  url: client_orders_path(@client.id),
                  method: :post,
                  html: { class: 'ls-form ' } do |form|%>
      <%= form.hidden_field :client_id, value: @client_id %>
      <%= form.hidden_field :user_id, value: current_user.id %>
      <%= form.hidden_field :plan_id, value: @plan.id %>
      <fieldset>
        <% @prices.each do |price| %>
          <div id='<%= price.period %>', style='margin: 15px 0 20px 15px' %>
            <%= price.period %><br>
            <%= number_to_currency(price.value) %>
          </div>
        <% end %>
      </fieldset>
      <fieldset style='margin: 15px 0 20px 0'>
      <%= form.label :period, 'Periodicidade', class: 'ls-label-text' %><br>
      <div class="dropdown">
        <%= form.collection_select :period, @prices, :period, :period %>
      </div>
      </fieldset>
      <fieldset>
        <%= form.submit 'Confirmar',class: "ls-btn-primary" %>
      </fieldset>
    <% end %>
  <% end %>
</div>
<%= link_to 'Voltar', :back, class: 'ls-btn ls-btn-sm', style: 'margin-top: -15px' %>