config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for :users
  root to: 'home#index'

  get 'search_clients', to: 'clients#search'
  get 'search_orders', to: 'orders#search'
  get 'plans', to: 'orders#plans'
  get 'values', to: 'orders#values'
  
  resources :orders, only: %i[index show edit update] do
    get 'canceled', to: 'orders#canceled', on: :collection
    get 'review_cancelation', to: 'orders#review_cancelation', on: :member
    patch :cancel_order , on: :member, as: 'cancel'
  end

  resources :commissions, only: %i[index]
    resources :sellers, only: %i[index new create show] do
    get 'commissions', on: :member
    patch :change_status, on: :member
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get '/orders/clients/:id', to: 'orders#clients', as: 'client'
      resources :orders, only: %i[show create] do
        patch 'pending', to: 'orders#pending'
        patch 'concluded', to: 'orders#concluded'
        patch 'canceled', to: 'orders#canceled'
      end
    end
  end
  
  resources :clients do
    resources :orders, only: %i[new create], on: :member
    get 'review_deactivation', to: 'clients#review_deactivation', on: :member
    patch :deactivate_cpf , on: :member
    patch :activate_cpf, on: :member
  end
end

app/views/layouts/_nav.html.erb
<div class="ls-topbar">    
      
  <div class="ls-notification-topbar">
    <% if user_signed_in? %>
      <div class="ls-alerts-list">
        <a href="#" class="ls-ico-bell-o" data-ls-module="topbarCurtain" data-target="#ls-notification-curtain"><span>Notificações</span></a>
        <a href="#" class="ls-ico-bullhorn" data-ls-module="topbarCurtain" data-target="#ls-help-curtain"><span>Ajuda</span></a>
        <a href="#" class="ls-ico-question" data-ls-module="topbarCurtain" data-target="#ls-feedback-curtain"><span>Sugestões</span></a>
      </div>
     
      <!--<div class="localogo">
        <%#= image_tag 'locaweb_logo.svg' %>
      </div> -->
     
    <div data-ls-module="dropdown" class="ls-dropdown ls-user-account">
    
      <a href="#" class="ls-ico-user">        
        <span class="ls-name">Olá, <%= current_user.name.split.first %></span>        
      </a>

      <nav class="ls-dropdown-nav ls-user-menu">
        <ul>
          <li><%= link_to 'Meus Dados', edit_user_registration_path %> </li>
          <li><%= link_to 'Sair', destroy_user_session_path,
                            method: :delete,                            
                            data: { confirm: 'Tem certeza de que deseja sair?' }%></li>
                            
        </ul>

        <% else %>        
        <%= link_to 'Entrar', new_user_session_path unless current_page?(controller: 'sessions', action: 'new') %>
        <% end %>
      </nav>
    </div>
  </div>
 <span class="ls-show-sidebar ls-ico-menu"> </span>
  <h1 class="ls-brand-name">
    <a href="/" class="ls-ico-earth">
      <small>Campus Code</small>
      Vendas
    </a>
  </h1>   

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="ls-theme-green">
  <head>
    <title>Vendas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <link href="http://assets.locaweb.com.br/locastyle/3.10.1/stylesheets/locastyle.css" rel="stylesheet" type="text/css">
    <link rel="icon" sizes="192x192" href="/locawebstyle/assets/images/ico-boilerplate.png">
    <link rel="apple-touch-icon" href="/locawebstyle/assets/images/ico-boilerplate.png">
    <link rel="stylesheet" type="text/css" href="//assets.locaweb.com.br/locastyle/3.10.1/stylesheets/locastyle.css">
  </head>

  <body>
    <%= render partial: "layouts/nav" %>
    <main class="ls-main"> 
      <div class="container-fluid">
        <p class="notice ls-alert-success"><%= notice %></p>
        <p class="alert ls-alert-danger"><%= alert %></p>      
      
        <%= yield %>   
      </div>  
    </main>

    <aside class="ls-sidebar">
      <div class="ls-sidebar-inner">
        <nav class="ls-menu">
          <ul>

            <li class=<%= current_page?(root_path) ? "ls-active" : "" %>>
              <%= link_to 'Início', root_path, class:"ls-ico-home" %>
            </li>
            <% if user_signed_in? %>

            <li class=<%= current_page?(clients_path) ? "ls-active" : "" %>>
              <%= link_to 'Clientes', clients_path, class:"ls-ico-users" %>
            </li>

            <li class=<%= current_page?(orders_path) ? "ls-active" : "" %>>
              <%= link_to 'Pedidos', orders_path, class: "ls-ico-edit-admin" %>
            </li> 

            <% if current_user.admin? %>

              <li class=<%= current_page?(sellers_path) ? "ls-active" : "" %>>
                <%= link_to 'Vendedores', sellers_path , class:"ls-ico-panel-pabx"%>
              </li>

              <li class=<%= current_page?(new_seller_path) ? "ls-active" : "" %>>
                <%= link_to 'Cadastrar vendedor', new_seller_path, class:"ls-ico-user-add" %>
              </li>              

            <% end %> 
                           
              <li>
                <% commission_text = current_user.admin? ? 'Comissões' : 'Minhas Comissões' %>
                <%= link_to commission_text, commissions_path, class:"ls-ico-trophy" %>
              </li>
            
          <% end %>
        </ul>
        </nav>
      </div>
    </aside>
    <script src="http://code.jquery.com/jquery-2.0.1.min.js"></script>
    <script src="http://assets.locaweb.com.br/locastyle/3.10.1/javascripts/locastyle.js"></script>
  </body>
</html>

app/views/layouts/search.html.erb
<%= form_with url: clients_path, method: :get do %>
    <%= label_tag :query, 'CPF do cliente' %>
    <%= text_field_tag :query %>
    <%= submit_tag 'Buscar', class: 'ls-btn' %>
  <% end %>